"""Tracks position, average entry, realized/unrealized PnL and equity from fills."""
from __future__ import annotations

from dataclasses import dataclass, field

from common.enums import Side
from common.events import OrderEvent


@dataclass
class PositionManager:
    initial_capital: float
    position: float = 0.0            # signed base qty (+long / -short)
    avg_price: float = 0.0
    realized_pnl: float = 0.0
    fees_paid: float = 0.0
    mark_price: float = 0.0
    _fill_count: int = 0
    trades: list[dict] = field(default_factory=list)

    def on_fill(self, event: OrderEvent) -> float:
        """Apply a fill; returns realized PnL generated by this fill."""
        if not event.is_fill:
            return 0.0
        qty = event.quantity
        price = event.price
        delta = qty * event.side.sign  # signed change in position
        realized = 0.0
        pos = self.position

        if pos == 0 or (pos > 0 and delta > 0) or (pos < 0 and delta < 0):
            # opening or increasing in same direction -> update average price
            new_abs = abs(pos) + abs(delta)
            self.avg_price = (self.avg_price * abs(pos) + price * abs(delta)) / new_abs
            self.position = pos + delta
        else:
            # reducing / closing / flipping
            closing = min(abs(pos), abs(delta))
            if pos > 0:           # long reduced by a sell
                realized += closing * (price - self.avg_price)
            else:                 # short reduced by a buy
                realized += closing * (self.avg_price - price)
            remaining = abs(delta) - closing
            self.position = pos + delta
            if abs(pos) <= abs(delta):
                # fully closed (and possibly flipped)
                self.avg_price = price if remaining > 0 else 0.0

        self.realized_pnl += realized
        self.fees_paid += event.fee
        self.mark_price = price
        self._fill_count += 1
        self.trades.append({
            "timestamp": event.timestamp, "side": event.side.value, "price": price,
            "qty": qty, "fee": event.fee, "realized_pnl": realized,
            "position_after": self.position, "reason": event.reason,
        })
        return realized

    def update_mark(self, price: float) -> None:
        self.mark_price = price

    @property
    def unrealized_pnl(self) -> float:
        if self.position == 0 or self.mark_price == 0:
            return 0.0
        if self.position > 0:
            return self.position * (self.mark_price - self.avg_price)
        return abs(self.position) * (self.avg_price - self.mark_price)

    @property
    def equity(self) -> float:
        return self.initial_capital + self.realized_pnl - self.fees_paid + self.unrealized_pnl

    @property
    def position_notional(self) -> float:
        return abs(self.position) * (self.mark_price or self.avg_price)

    def snapshot(self) -> dict:
        return {
            "position": self.position,
            "avg_price": self.avg_price,
            "mark_price": self.mark_price,
            "realized_pnl": self.realized_pnl,
            "unrealized_pnl": self.unrealized_pnl,
            "fees_paid": self.fees_paid,
            "equity": self.equity,
            "position_notional": self.position_notional,
            "num_fills": self._fill_count,
        }